/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void queueTest() {
        String sample = "the quick brown fox jumps over the lazy dog";
        Queue<String> temp = new Queue<>();

        for(String s : sample.split("\\s+"))
            temp.enqueue(s);

        assertEquals(temp.toString(), " dog lazy the over jumps fox brown quick the");
    }
}
